apiVersion: skaffold/v2beta24
kind: Config
deploy:
  helm:
    hooks:
      after:
        - host:
            command:
              [
                "sh",
                "-c",
                "kubectl wait --for condition=Healthy --timeout=300s providers.pkg.crossplane.io/upbound-provider-aws",
              ]
    releases:
      - name: universal-crossplane
        repo: https://charts.upbound.io/stable/
        remoteChart: universal-crossplane
        namespace: upbound-system
        createNamespace: true
        valuesFiles:
          - tests/uxp-values.yaml
        version: 1.11.3-up.1
        wait: true
  kubectl:
    hooks:
      after:
        - host:
            command:
              [
                "sh",
                "-c",
                "kubectl kuttl test --test ./tests/compositions/; exit 0",
              ]
    manifests:
      - package/network/definition.yaml
      - package/network/composition.yaml
      # This file can only be un-commented once the XRD is healthy in the Control Plane
      - examples/network.yaml
