apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  # Install Universal Crossplane (uxp).
  - command: helm install universal-crossplane https://charts.upbound.io/stable/universal-crossplane-1.11.3-up.1.tgz --namespace upbound-system --wait --create-namespace --values tests/uxp-values.yaml
  # Wait for provider-cards to become healthy.
  - command: kubectl wait --for=condition=Healthy --timeout=300s "providers.pkg.crossplane.io/bmutziu-provider-cards"
  # Set up a table for play
  - command: kubectl apply -f "${PWD}/tests/init.yaml"
testDirs:
  - tests/
startKIND: true
kindContext: kuttl-test
skipClusterDelete: false
