apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  # Install Universal Crossplane (uxp).
  - command: helm install universal-crossplane https://charts.upbound.io/stable/universal-crossplane-1.11.3-up.1.tgz --namespace upbound-system --wait --create-namespace --values tests/uxp-values.yaml
  # Wait for provider-aws to become healthy.
  - command: kubectl wait "providers.pkg.crossplane.io/upbound-provider-aws" --for=condition=Installed --timeout=180s
  - command: kubectl wait "providers.pkg.crossplane.io/upbound-provider-aws" --for=condition=Healthy --timeout=600s
  # Install ProviderConfig for test.
  - command: kubectl apply -f tests/init/
testDirs:
  - tests/compositions/
startKIND: true
kindContext: kuttl-test
skipClusterDelete: false
